/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppUserRole = { 'client' : null } |
  { 'musician' : null } |
  { 'admin' : null } |
  { 'staff' : null };
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface Message {
  'id' : bigint,
  'content' : string,
  'channelId' : string,
  'authorName' : string,
  'timestamp' : bigint,
  'authorPrincipal' : Principal,
}
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export interface RoomSlot {
  'hourStart' : bigint,
  'dayOfWeek' : bigint,
  'room' : string,
  'available' : boolean,
  'hourEnd' : bigint,
}
export interface StudioEvent {
  'id' : bigint,
  'startTime' : bigint,
  'title' : string,
  'endTime' : bigint,
  'createdBy' : Principal,
  'room' : [] | [string],
  'description' : string,
}
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'status' : UserStatus,
  'shareContact' : boolean,
  'displayName' : string,
  'joinedAt' : bigint,
  'role' : AppUserRole,
  'email' : [] | [string],
  'avatarUrl' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserStatus = { 'active' : null } |
  { 'banned' : null } |
  { 'suspended' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banMember' : ActorMethod<[Principal], undefined>,
  'bootstrapAdmin' : ActorMethod<[string, [] | [string]], undefined>,
  'createEvent' : ActorMethod<
    [string, string, bigint, bigint, [] | [string]],
    bigint
  >,
  'deleteEvent' : ActorMethod<[bigint], undefined>,
  'deleteMessage' : ActorMethod<[bigint], undefined>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAllMembers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEvents' : ActorMethod<[], Array<StudioEvent>>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getMessages' : ActorMethod<[string], Array<Message>>,
  'getRoomAvailability' : ActorMethod<[], Array<RoomSlot>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAdminAssigned' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isCallerRegistered' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'postMessage' : ActorMethod<[string, string], bigint>,
  'register' : ActorMethod<[string, [] | [string]], undefined>,
  'registerWithInviteCode' : ActorMethod<
    [string, string, [] | [string]],
    undefined
  >,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setRoomAvailability' : ActorMethod<[Array<RoomSlot>], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'updateMemberRole' : ActorMethod<[Principal, AppUserRole], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];