/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const PollOption = IDL.Record({
  'voteCount' : IDL.Nat,
  'text' : IDL.Text,
});
export const Poll = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'votes' : IDL.Vec(IDL.Principal),
  'createdAt' : Time,
  'multiSelect' : IDL.Bool,
  'isActive' : IDL.Bool,
  'anonymous' : IDL.Bool,
  'options' : IDL.Vec(PollOption),
});
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const UserStatus = IDL.Variant({
  'active' : IDL.Null,
  'banned' : IDL.Null,
  'suspended' : IDL.Null,
});
export const AppUserRole = IDL.Variant({
  'client' : IDL.Null,
  'musician' : IDL.Null,
  'admin' : IDL.Null,
  'staff' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'status' : UserStatus,
  'shareContact' : IDL.Bool,
  'displayName' : IDL.Text,
  'joinedAt' : IDL.Int,
  'role' : AppUserRole,
  'email' : IDL.Opt(IDL.Text),
  'avatarUrl' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const StudioEvent = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Int,
  'title' : IDL.Text,
  'endTime' : IDL.Int,
  'createdBy' : IDL.Principal,
  'room' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
});
export const FreeTimeSlot = IDL.Record({
  'id' : IDL.Nat,
  'timeStart' : IDL.Text,
  'note' : IDL.Text,
  'room' : IDL.Text,
  'dayLabel' : IDL.Text,
  'timeEnd' : IDL.Text,
});
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'channelId' : IDL.Text,
  'authorName' : IDL.Text,
  'timestamp' : IDL.Int,
  'authorPrincipal' : IDL.Principal,
});
export const RoomSlot = IDL.Record({
  'hourStart' : IDL.Nat,
  'dayOfWeek' : IDL.Nat,
  'room' : IDL.Text,
  'available' : IDL.Bool,
  'hourEnd' : IDL.Nat,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFreeTimeSlot' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addReaction' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'adminDeleteMessage' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'banUser' : IDL.Func([IDL.Principal], [IDL.Text], []),
  'checkIfCallerIsAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'createEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, IDL.Int, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'createPoll' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Bool, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'deleteEvent' : IDL.Func([IDL.Nat], [], []),
  'deleteMessage' : IDL.Func([IDL.Nat], [], []),
  'deletePoll' : IDL.Func([IDL.Nat], [], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getAllPolls' : IDL.Func([], [IDL.Vec(Poll)], ['query']),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEvents' : IDL.Func([], [IDL.Vec(StudioEvent)], ['query']),
  'getFreeTimeSlots' : IDL.Func([], [IDL.Vec(FreeTimeSlot)], ['query']),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
  'getPoll' : IDL.Func([IDL.Nat], [IDL.Opt(Poll)], ['query']),
  'getPollResults' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Opt(
          IDL.Record({
            'results' : IDL.Vec(IDL.Nat),
            'hasVoted' : IDL.Bool,
            'options' : IDL.Vec(PollOption),
          })
        ),
      ],
      ['query'],
    ),
  'getReactions' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Principal)))],
      ['query'],
    ),
  'getRoomAvailability' : IDL.Func([], [IDL.Vec(RoomSlot)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserVotes' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Nat)], ['query']),
  'hasVotedInPoll' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerRegistered' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'postMessage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'register' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'removeFreeTimeSlot' : IDL.Func([IDL.Nat], [], []),
  'removeUser' : IDL.Func([IDL.Principal], [IDL.Text], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setRoomAvailability' : IDL.Func([IDL.Vec(RoomSlot)], [], []),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'unbanUser' : IDL.Func([IDL.Principal], [IDL.Text], []),
  'vote' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const PollOption = IDL.Record({ 'voteCount' : IDL.Nat, 'text' : IDL.Text });
  const Poll = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'votes' : IDL.Vec(IDL.Principal),
    'createdAt' : Time,
    'multiSelect' : IDL.Bool,
    'isActive' : IDL.Bool,
    'anonymous' : IDL.Bool,
    'options' : IDL.Vec(PollOption),
  });
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const UserStatus = IDL.Variant({
    'active' : IDL.Null,
    'banned' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const AppUserRole = IDL.Variant({
    'client' : IDL.Null,
    'musician' : IDL.Null,
    'admin' : IDL.Null,
    'staff' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'status' : UserStatus,
    'shareContact' : IDL.Bool,
    'displayName' : IDL.Text,
    'joinedAt' : IDL.Int,
    'role' : AppUserRole,
    'email' : IDL.Opt(IDL.Text),
    'avatarUrl' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const StudioEvent = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Int,
    'title' : IDL.Text,
    'endTime' : IDL.Int,
    'createdBy' : IDL.Principal,
    'room' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
  });
  const FreeTimeSlot = IDL.Record({
    'id' : IDL.Nat,
    'timeStart' : IDL.Text,
    'note' : IDL.Text,
    'room' : IDL.Text,
    'dayLabel' : IDL.Text,
    'timeEnd' : IDL.Text,
  });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'channelId' : IDL.Text,
    'authorName' : IDL.Text,
    'timestamp' : IDL.Int,
    'authorPrincipal' : IDL.Principal,
  });
  const RoomSlot = IDL.Record({
    'hourStart' : IDL.Nat,
    'dayOfWeek' : IDL.Nat,
    'room' : IDL.Text,
    'available' : IDL.Bool,
    'hourEnd' : IDL.Nat,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFreeTimeSlot' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addReaction' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'adminDeleteMessage' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'banUser' : IDL.Func([IDL.Principal], [IDL.Text], []),
    'checkIfCallerIsAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'createEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, IDL.Int, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'createPoll' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Bool, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'deleteEvent' : IDL.Func([IDL.Nat], [], []),
    'deleteMessage' : IDL.Func([IDL.Nat], [], []),
    'deletePoll' : IDL.Func([IDL.Nat], [], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getAllPolls' : IDL.Func([], [IDL.Vec(Poll)], ['query']),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEvents' : IDL.Func([], [IDL.Vec(StudioEvent)], ['query']),
    'getFreeTimeSlots' : IDL.Func([], [IDL.Vec(FreeTimeSlot)], ['query']),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
    'getPoll' : IDL.Func([IDL.Nat], [IDL.Opt(Poll)], ['query']),
    'getPollResults' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Opt(
            IDL.Record({
              'results' : IDL.Vec(IDL.Nat),
              'hasVoted' : IDL.Bool,
              'options' : IDL.Vec(PollOption),
            })
          ),
        ],
        ['query'],
      ),
    'getReactions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Principal)))],
        ['query'],
      ),
    'getRoomAvailability' : IDL.Func([], [IDL.Vec(RoomSlot)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserVotes' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Nat)], ['query']),
    'hasVotedInPoll' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerRegistered' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'postMessage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'register' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'removeFreeTimeSlot' : IDL.Func([IDL.Nat], [], []),
    'removeUser' : IDL.Func([IDL.Principal], [IDL.Text], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setRoomAvailability' : IDL.Func([IDL.Vec(RoomSlot)], [], []),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'unbanUser' : IDL.Func([IDL.Principal], [IDL.Text], []),
    'vote' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };